[package]
name = "afrxo/glue"
description = "Another game framework."
version = "6.1.7"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "bundle.project.json", "LICENSE"]

[dependencies]
Promise = "evaera/promise@4.0.0"