name: Github Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'
    
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Install Node Dependencies
        run: npm install

      - name: Install Aftman Tools
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          version: "^1.0.0"
          token: ${{ github.token }}

      - name: Set Version
        id: set_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build File
        run: bash build.sh
        
      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.set_version.outputs.VERSION }}
          body: CHANGELOG.md
          files: Glue.rbxm

